# Generated by Django 3.2.3 on 2025-06-08 18:02

from django.db import migrations, models

import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', validators=[recipes.validators.validate_image_size, recipes.validators.validate_image_extension], verbose_name='Картинка'),
        ),
    ]
