# Generated by Django 3.2.3 on 2025-05-22 10:01

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/', validators=[recipes.validators.validate_image_size, recipes.validators.validate_image_extension], verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.validators.validate_hex_color], verbose_name='Цвет в HEX'),
        ),
    ]
