# Generated by Django 3.2.3 on 2025-05-22 10:01

from django.db import migrations, models

import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[recipes.validators.CustomEmailValidator()], verbose_name='Email'),
        ),
    ]
